name:  feature request
description: Create a feature request to add some value to this project.
title: "[PROJECT] <project description>"
labels: [enhancement]
body:
  - type: textarea
    id: projectDescription
    attributes:
      label: Description of the project, you want to add.
    validations:
      required: true
  - type: textarea
    id: workingenvironment
    attributes:
      label: Mention if this feature is for any specific Working Environment (e.g. operating system, browser, device, N/A) 
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Please add some pictorial references to the prooject, if applicable (Drag & Drop your ss below)
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: What will be your aprroach to add this project?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Any other context you have, to add here regarding this project.
    validations:
      required: false